### ISSUE TITLE
Future Design

### ISSUE THREAD

**Issue by techalchemy** [sarugaku/pip-shims#37]
For the future design of this project, I think we need to make a decision about the approach we want to take.  Already in the tests there is a lot of conditional checking just to test the APIs we are even exposing.  For example:

```python
        if parse_version(pip_version) > parse_version("19.99.99"):
            preparer_kwargs.update(
                {"session": session, "finder": finder,}
            )
        else:
            resolver_kwargs["session"] = session
        if parse_version(pip_version) >= parse_version("19.3"):
            make_install_req = partial(
                install_req_from_req_string,
                isolated=False,
                wheel_cache=wheel_cache,
                # use_pep517=use_pep517,
            )
            resolver_kwargs["make_install_req"] = make_install_req
        else:
            resolver_kwargs.update(
                {"isolated": False, "wheel_cache": wheel_cache,}
            )
```

One thing I was thinking about is that all of the changes in pip are still ultimately going to mean everyone who is consuming this library will have to change their own code.  It doesn't have to be that way though, it is possible to simply write the conditional checks into the library as a compatibility layer here, providing a backward compatible way of invoking pip that simply translates the supplied arguments.  I don't really know why I wasn't doing that already, I just haven't had the time or energy to spend on the design of this beyond the ridiculous import hacks.

I do have time now. Thoughts?

**Comment by uranusjr** [comment]
The problem with the described approach from what I can tell is that pip sometimes move implementations in/out of a function from/to the call site, so the same name does not necessarily mean the same thing across versions. In this case you’d need to design a higher level interface that is different from pip’s, and that could be a lot of work depending on what you do. But I do think the described design is better than the current one.
