### ISSUE TITLE
Missing git tag for 0.3.4 release

### ISSUE THREAD

**Issue by felixonmars** [sarugaku/pip-shims#39]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by techalchemy** [comment]
hrm, thanks for the note, I wonder why... suspect azure didn't push this correctly

**Comment by techalchemy** [comment]
I should warn you not to get too excited, the release is slightly short of working perfectly and the refactor will be significantly better and is just  finished I believe

**Comment by felixonmars** [comment]
Understood, thanks!
