### ISSUE TITLE
Fix test failures

### ISSUE THREAD

**Issue by brainwane** [sarugaku/pip-shims#58]
@techalchemy what are the specific current test failures that need fixing?

**Comment by brainwane** [comment]
(Resolving this will also help with https://github.com/pypa/pipenv/issues/4058#issuecomment-565550646 and https://github.com/pypa/pipenv/issues/3369 , since `pip-shims` problems are blocking the pipenv release.)

**Comment by techalchemy** [comment]
`InstallRequirement.ensure_build_location` now takes an additional argument on `pip@master` -- `autodelete`:

```TypeError: ensure_build_location() missing 1 required positional argument: 'autodelete'```

`WheelCache` instances are now built from temporary directories which require a `global_tempdir_manager` context (so will require a shim on `pip >= 20`)
