### ISSUE TITLE
[Security] Workflow pypi_upload.yml is using vulnerable action actions/checkout

### ISSUE THREAD

**Issue by igibek** [sarugaku/pip-shims#78]
The workflow pypi_upload.yml is referencing action actions/checkout using references v1. However this reference is missing the commit [a6747255bd19d7a757dbdda8c654a9f84db19839](https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by matteius** [comment]
@igibek I am looking at this report and it seems that @frostming updated the pypi_upload.yml on 11/2/2021 which was before this report was opened, but it appears to be using `actions/checkout@v2`.   Can you confirm if this is still an issue or not?

**Comment by igibek** [comment]
I can confirm that it was resolved. Probably our dataset was outdated before we notified you.
